# -*- coding: utf-8 -*-
# Generated by Django 1.11.4 on 2017-08-28 19:12
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion
import uuid


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='TestNode',
            fields=[
                ('id', models.UUIDField(default=uuid.UUID('542b74c1-13a0-4f93-baa8-b12a404282eb'), editable=False, primary_key=True, serialize=False)),
                ('level', models.IntegerField(help_text="The level of the node, in relation to it's height in the tree. Starts at root, with level = 1.")),
                ('path', models.TextField(help_text="A CSV list of the ids leading to this Node. Root will be a list of one item, it's own id.")),
                ('parent_node', models.ForeignKey(blank=True, help_text='The parent of this Node. Will be None if a root.', null=True, on_delete=django.db.models.deletion.CASCADE, related_name='node_parent_node', to='django_ancestry_relation.TestNode')),
                ('root_node', models.ForeignKey(help_text='The root node of this tree. If this node is root, this reference self.', on_delete=django.db.models.deletion.CASCADE, related_name='node_root_node', to='django_ancestry_relation.TestNode')),
            ],
            options={
                'abstract': False,
            },
        ),
    ]
