# -*- coding: utf-8 -*-
# Generated by Django 1.11.4 on 2017-08-28 20:07
from __future__ import unicode_literals

from django.db import migrations, models
import uuid


class Migration(migrations.Migration):

    dependencies = [
        ('django_ancestry_relation', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='testnode',
            name='data',
            field=models.CharField(blank=True, max_length=50),
        ),
        migrations.AlterField(
            model_name='testnode',
            name='id',
            field=models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False),
        ),
    ]
